language: node_js
node_js:
  - "4.2"
before_install:
  - npm install node-pre-gyp
script:
  - npm run-script test
env:
  - NODE_ENV=test
  - CXX=clang-3.6
compiler: clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
