language: node_js
before_install:
    - npm install node-pre-gyp
script:
    - npm run-script test
env:
    - NODE_ENV=test
    - CXX=g++-4.8
node_js:
  - "4.2"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
