language: node_js
node_js:
  - "4.2"
branches:
  only:
    - master
    - development
before_install:
  - npm install node-pre-gyp
script:
  - npm run-script test
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=test CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
