#!/bin/bash

### BEGIN INIT INFO
# Provides:             formideos
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description:    FormideOS client, driver, slicer and dashboard
### END INIT INFO

case "$1" in

    start)
        cd /home/debian/formideOS/formideOS-drivers/ClientDriver/Debug
        sudo ./ClientDriver &

        cd /home/debian/formideOS/formideOS-drivers/formideOS/Debug
        sudo ./formideOS &

        cd /home/debian/formideOS/katana-slicer/katana/Debug
        sudo ./katana &

        cd /home/debian/formideOS/formideOS-client
        sudo node bootstrap.js
    ;;

    *)
		echo "Usage: /etc/init.d/formideos {start}"
		exit 1
	;;

esac