FormideClient.log.info("                                        ");
FormideClient.log.info("                   ?                    ");
FormideClient.log.info("                 ????                   ");
FormideClient.log.info("               7??????                  ");
FormideClient.log.info("              ??  ?? ??                 ");
FormideClient.log.info("            ++    +   ?+                ");
FormideClient.log.info("          ++      +    I+               ");
FormideClient.log.info("          +      ++     7+              ");
FormideClient.log.info("         7+      +?      ++             ");
FormideClient.log.info("         ++      +      ++ +            ");
FormideClient.log.info("         +       +      +   +           ");
FormideClient.log.info("        ++      ++   7+++    +          ");
FormideClient.log.info("        +       +++++  ++     +         ");
FormideClient.log.info("       ?+      +?+      +     ++        ");
FormideClient.log.info("       +?    ++   +     ++    7+        ");
FormideClient.log.info("       +    ++   ++++++  +     +        ");
FormideClient.log.info("      ++  ++ +++++   + ++++    ++       ");
FormideClient.log.info("      ++++       ++++    I++   ?+       ");
FormideClient.log.info("     +=            =        ==  =       ");
FormideClient.log.info("      ==           =         =  ==      ");
FormideClient.log.info("       ==         ==         ====       ");
FormideClient.log.info("        ==       ====        ==         ");
FormideClient.log.info("         ==    ==   I==     ==          ");
FormideClient.log.info("          =====        ==I7=7           ");
FormideClient.log.info("           ================             ");
FormideClient.log.info("                                        ");