FormideOS.log.info("                                        ");				
FormideOS.log.info("                   ?                    ");
FormideOS.log.info("                 ????                   ");
FormideOS.log.info("               7??????                  ");
FormideOS.log.info("              ??  ?? ??                 ");
FormideOS.log.info("            ++    +   ?+                ");
FormideOS.log.info("          ++      +    I+               ");
FormideOS.log.info("          +      ++     7+              ");
FormideOS.log.info("         7+      +?      ++             ");
FormideOS.log.info("         ++      +      ++ +            ");
FormideOS.log.info("         +       +      +   +           ");
FormideOS.log.info("        ++      ++   7+++    +          ");
FormideOS.log.info("        +       +++++  ++     +         ");
FormideOS.log.info("       ?+      +?+      +     ++        ");
FormideOS.log.info("       +?    ++   +     ++    7+        ");
FormideOS.log.info("       +    ++   ++++++  +     +        ");
FormideOS.log.info("      ++  ++ +++++   + ++++    ++       ");
FormideOS.log.info("      ++++       ++++    I++   ?+       ");
FormideOS.log.info("     +=            =        ==  =       ");
FormideOS.log.info("      ==           =         =  ==      ");
FormideOS.log.info("       ==         ==         ====       ");
FormideOS.log.info("        ==       ====        ==         ");
FormideOS.log.info("         ==    ==   I==     ==          ");
FormideOS.log.info("          =====        ==I7=7           ");
FormideOS.log.info("           ================             ");
FormideOS.log.info("                                        ");